/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AbaCameraConteudo: typeof import('./src/components/abas/AbaCameraConteudo.vue')['default']
    AbaExperiencia: typeof import('./src/components/curriculo/editor/abas/AbaExperiencia.vue')['default']
    AbaExploradorConteudo: typeof import('./src/components/abas/AbaExploradorConteudo.vue')['default']
    AbaExtensoesConteudo: typeof import('./src/components/abas/AbaExtensoesConteudo.vue')['default']
    AbaFormacao: typeof import('./src/components/curriculo/editor/abas/AbaFormacao.vue')['default']
    AbaGitConteudo: typeof import('./src/components/abas/AbaGitConteudo.vue')['default']
    AbaHabilidades: typeof import('./src/components/curriculo/editor/abas/AbaHabilidades.vue')['default']
    AbaIdiomas: typeof import('./src/components/curriculo/editor/abas/AbaIdiomas.vue')['default']
    AbaLinks: typeof import('./src/components/curriculo/editor/abas/AbaLinks.vue')['default']
    AbaPesquisaConteudo: typeof import('./src/components/abas/AbaPesquisaConteudo.vue')['default']
    AbaPessoais: typeof import('./src/components/curriculo/editor/abas/AbaPessoais.vue')['default']
    AbaProjetos: typeof import('./src/components/curriculo/editor/abas/AbaProjetos.vue')['default']
    BemVindo: typeof import('./src/components/bemVindo/BemVindo.vue')['default']
    Curriculo: typeof import('./src/components/curriculo/Curriculo.vue')['default']
    EditorAbas: typeof import('./src/components/EditorAbas.vue')['default']
    EditorConteudo: typeof import('./src/components/EditorConteudo.vue')['default']
    EditorCurriculoConteudo: typeof import('./src/components/curriculo/editor/EditorCurriculoConteudo.vue')['default']
    EditoresAbertos: typeof import('./src/components/abas/EditoresAbertos.vue')['default']
    Experiencia: typeof import('./src/components/curriculo/Experiencia.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Formacao: typeof import('./src/components/curriculo/Formacao.vue')['default']
    Fotos: typeof import('./src/components/Fotos.vue')['default']
    Habilidades: typeof import('./src/components/curriculo/Habilidades.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    Idiomas: typeof import('./src/components/curriculo/Idiomas.vue')['default']
    IframeViewer: typeof import('./src/components/IframeViewer.vue')['default']
    InfoPessoais: typeof import('./src/components/curriculo/InfoPessoais.vue')['default']
    ItemArvore: typeof import('./src/components/abas/ItemArvore.vue')['default']
    Layout: typeof import('./src/components/layout/Layout.vue')['default']
    Links: typeof import('./src/components/curriculo/Links.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    MarkdownViewer: typeof import('./src/components/MarkdownViewer.vue')['default']
    MenuConfiguracoes: typeof import('./src/components/MenuConfiguracoes.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PainelLateral: typeof import('./src/components/PainelLateral.vue')['default']
    Projetos: typeof import('./src/components/curriculo/Projetos.vue')['default']
    Readme: typeof import('./src/components/bemVindo/Readme.vue')['default']
    Resumo: typeof import('./src/components/curriculo/Resumo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeletorTemas: typeof import('./src/components/SeletorTemas.vue')['default']
    Setup: typeof import('./src/components/bemVindo/Setup.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    Vscode: typeof import('./src/components/Vscode.vue')['default']
  }
}
