export default {
  perfil: {
    avatar_url:'',
    name: '',
    login: '',
    location: '',
  },
  contributions: '',
  readme: '',
  readmePerfil: '',
  repositorios: null,
  // repositorios: {
  //   id: 0,
  //   node_id: "",
  //   name: "",
  //   full_name: "",
  //   private: false,
  //   owner: {},
  //   html_url: "",
  //   description: null,
  //   language: null,
  //   fork: false,
  //   url: "",
  // },
};